# Generated by Django 5.1.1 on 2025-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='license_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
